<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            ['programme_id' => 2, 'department_id' => 1, 'name' => 'ND Business Administration and Management'],
            ['programme_id' => 1, 'department_id' => 1, 'name' => 'HND Business Administration and Management'],
            ['programme_id' => 3, 'department_id' => 1, 'name' => 'NDS Business Administration and Management'],
            ['programme_id' => 5, 'department_id' => 1, 'name' => 'Diploma in Personnel Management'],
            ['programme_id' => 5, 'department_id' => 1, 'name' => 'Diploma in Office Technology and management'],
            ['programme_id' => 6, 'department_id' => 1, 'name' => 'PGD Business Administration and Management'],
            ['programme_id' => 1, 'department_id' => 2, 'name' => 'HND Marketing'],
            ['programme_id' => 2, 'department_id' => 2, 'name' => 'ND Marketing'],
            ['programme_id' => 3, 'department_id' => 2, 'name' => 'NDS Marketing'],
            ['programme_id' => 5, 'department_id' => 3, 'name' => 'PD Marketing'],
            ['programme_id' => 1, 'department_id' => 3, 'name' => 'HND Public Administration'],
            ['programme_id' => 2, 'department_id' => 3, 'name' => 'ND Public Administration'],
            ['programme_id' => 3, 'department_id' => 3, 'name' => 'NDS Public Administration'],
            ['programme_id' => 5, 'department_id' => 3, 'name' => 'PD Public Administration'],
            ['programme_id' => 6, 'department_id' => 3, 'name' => 'PGD Public Administration'],
            ['programme_id' => 2, 'department_id' => 4, 'name' => 'ND Local Government'],
            ['programme_id' => 5, 'department_id' => 4, 'name' => 'Diploma Local Government'],
            ['programme_id' => 2, 'department_id' => 4, 'name' => 'ND Local Government'],
            ['programme_id' => 1, 'department_id' => 5, 'name' => 'HND Accountancy'],
            ['programme_id' => 2, 'department_id' => 5, 'name' => 'ND Accountancy'],
            ['programme_id' => 3, 'department_id' => 5, 'name' => 'NDS Accountancy'],
            ['programme_id' => 5, 'department_id' => 5, 'name' => 'PD Accountancy'],
            ['programme_id' => 6, 'department_id' => 5, 'name' => 'PGD Accounting and Finance'],


            ['programme_id' => 1, 'department_id' => 6, 'name' => 'HND Banking and Finance'],
            ['programme_id' => 2, 'department_id' => 6, 'department_id' => 6, 'name' => 'ND Banking and Finance'],
            ['programme_id' => 3, 'department_id' => 6, 'name' => 'NDS Banking and Finance'],
            ['programme_id' => 5, 'department_id' => 6, 'name' => 'PD Banking and Finance'],
            ['programme_id' => 1,  'department_id' => 7, 'name' => 'HND Mechanical Engineering (Production)'],
            ['programme_id' => 1, 'department_id' => 7, 'name' => 'HND Mechanical Engineering (Power & Machine)'],
            ['programme_id' => 2, 'department_id' => 7, 'name' => 'ND Mechanical Engineering'],
            ['programme_id' => 3, 'department_id' => 7, 'name' => 'NDS Mechanical Engineering'],
            ['programme_id' => 5, 'department_id' => 7, 'name' => 'Diploma in Mechanical Engineering'],
            ['programme_id' => 6, 'department_id' => 7, 'name' => 'PGD Mechanical Engineering'],
            ['programme_id' => 1, 'department_id' => 8, 'name' => 'HND Metallurgical Engineering'],
            ['programme_id' => 2, 'department_id' => 8, 'name' => 'ND Metallurgical Engineering'],
            ['programme_id' => 3, 'department_id' => 8, 'name' => 'NDS Metallurgical Engineering'],
            ['programme_id' => 1, 'department_id' => 9, 'name' => 'HND Electrical Engineering Technology(POWER AND MACHINE)'],
            ['programme_id' => 1, 'department_id' => 9, 'name' => 'HND ELECTRICAL ENGINEERING (ELECT. AND TELECOMMUNICATIONS)'],
            ['programme_id' => 2, 'department_id' => 9, 'name' => 'ND Electrical Engineering Technology'],
            ['programme_id' => 3, 'department_id' => 9, 'name' => 'NDS Electrical Engineering Technology'],
            ['programme_id' => 6, 'department_id' => 9, 'name' => 'PGD Electrical Engineering'],
            ['programme_id' => 5, 'department_id' => 9, 'name' => 'Diploma Electrical Engineering'],
            ['programme_id' => 1, 'department_id' => 10, 'name' => 'HND Agricultural Engineering (Farm Power Machinery)'],
            ['programme_id' => 1, 'department_id' => 10, 'name' => 'HND Agricultural Engineering (Soil & Water Engineering)'],
            ['programme_id' => 2, 'department_id' => 10, 'name' => 'ND Agricultural Engineering Technology'],
            ['programme_id' => 3, 'department_id' => 10, 'name' => 'NDS Agricultural Engineering Technology'],
            ['programme_id' => 2, 'department_id' => 10, 'name' => 'ND Agricultural Technology'],
            ['programme_id' => 5, 'department_id' => 10, 'name' => 'Diploma in Agric Engineering'],
            ['programme_id' => 6, 'department_id' => 10, 'name' => 'Soil and Water Option'],
            ['programme_id' => 6, 'department_id' => 10, 'name' => 'Agric Mechanization Option'],
            ['programme_id' => 1, 'department_id' => 11, 'name' => 'HND Civil Engineering Technology'],
            ['programme_id' => 2, 'department_id' => 11, 'name' => 'ND Civil Engineering Technology'],
            ['programme_id' => 3, 'department_id' => 11, 'name' => 'NDS Civil Engineering Technology'],
            ['programme_id' => 5, 'department_id' => 11, 'name' => 'Diploma in Civil Engineering'],
            ['programme_id' => 6, 'department_id' => 11, 'name' => 'PGD Civil Engineering'],
            ['programme_id' => 1, 'department_id' => 12, 'name' => 'HND Architectural Technology'],
            ['programme_id' => 2, 'department_id' => 12, 'name' => 'ND Architectural Technology'],
            ['programme_id' => 3, 'department_id' => 12, 'name' => 'NDS Architectural Technology'],
            ['programme_id' => 5, 'department_id' => 12, 'name' => 'Diploma Architectural Technology'],
            ['programme_id' => 6, 'department_id' => 12, 'name' => 'PGD Architectural Technology'],
            ['programme_id' => 1, 'department_id' => 13, 'name' => 'HND Building Technology'],
            ['programme_id' => 2, 'department_id' => 13, 'name' => 'ND Building Technology'],
            ['programme_id' => 5, 'department_id' => 13, 'name' => 'Diploma in Building Technology'],
            ['programme_id' => 6, 'department_id' => 13, 'name' => 'PGD in Building Technology'],
            ['programme_id' => 1, 'department_id' => 14, 'name' => 'HND Urban and Regional Planning'],
            ['programme_id' => 2, 'department_id' => 14, 'name' => 'ND Urban and Regional Planning'],
            ['programme_id' => 3, 'department_id' => 14, 'name' => 'NDS Urban and Regional Planning'],
            ['programme_id' => 6, 'department_id' => 14, 'name' => 'Professional Diploma in URP'],
            ['programme_id' => 1, 'department_id' => 15, 'name' => 'HND Quantity Surveying'],
            ['programme_id' => 2, 'department_id' => 15, 'name' => 'ND Quantity Surveying'],
            ['programme_id' => 3,  'department_id' => 15, 'name' => 'NDS Quantity Surveying'],
            ['programme_id' => 5, 'department_id' => 15, 'name' => 'Diploma in Quantity Surveying'],
            ['programme_id' => 1,  'department_id' => 16, 'name' => 'HND Estate Management'],
            ['programme_id' => 2, 'department_id' => 16, 'name' => 'ND Estate Management'],
            ['programme_id' => 3,  'department_id' => 16, 'name' => 'NDS Estate Management'],
            ['programme_id' => 5, 'department_id' => 16, 'name' => 'Diploma in Estate Management'],
            ['programme_id' => 6, 'department_id' => 16, 'name' => 'PGD Estate Management and Evaluation '],
            ['programme_id' => 1, 'department_id' => 17, 'name' => 'HND Surveying and Geo-Informatics'],
            ['programme_id' => 2,  'department_id' => 17, 'name' => 'ND Surveying and Geo-Informatics'],
            ['programme_id' => 3,  'department_id' => 17, 'name' => 'NDS Surveying and Geo-Informatics'],
            ['programme_id' => 4,  'department_id' => 18, 'name' => 'Industrial Education(NCE)'],
            ['programme_id' => 4,  'department_id' => 19, 'name' => 'Business Education(NCE)'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'COMPUTER EDUCATION/BIOLOGY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'COMPUTER EDUCATION/CHEMISTRY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'COMPUTER EDUCATION/PHYSICS'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'COMPUTER EDUCATION/MATHEMATICS'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'COMPUTER EDUCATION/INTEGRATED SCIENCE'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'MATHEMATICS/ BIOLOGY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'MATHEMATICS /CHEMISTRY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'MATHEMATICS /PHYSICS'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'MATHEMATICS/ INTEGRATED SCIENCE'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'INTEGRATED SCIENCE/ BIOLOGY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'INTEGRATED SCIENCE/CHEMISTRY'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'INTEGRATED SCIENCE/ PHYSICS'],
            ['programme_id' => 4,  'department_id' => 25, 'name' => 'INTEGRATED SCIENCE(DOUBLE MAJOR)'],
            ['programme_id' => 1,  'department_id' => 20, 'name' => 'HND Computer Science'],
            ['programme_id' => 2,  'department_id' => 20, 'name' => 'ND Computer Science'],
            ['programme_id' => 3,  'department_id' => 20, 'name' => 'NDS Computer Science'],
            ['programme_id' => 1,  'department_id' => 21, 'name' => 'HND Statistics'],
            ['programme_id' => 2,  'department_id' => 21, 'name' => 'ND Statistics'],
            ['programme_id' => 3,  'department_id' => 21, 'name' => 'HND Statistics'],
            ['programme_id' => 5,  'department_id' => 21, 'name' => 'PD Statistics'],
            ['programme_id' => 6,  'department_id' => 21, 'name' => 'PGD Statistics'],
            ['programme_id' => 1,  'department_id' => 22, 'name' => 'HND SLT Physics with Electronics'],
            ['programme_id' => 1,  'department_id' => 22, 'name' => 'HND SLT Microbiology/Biochemistry'],
            ['programme_id' => 1,  'department_id' => 22, 'name' => 'HND SLT Chemistry'],
            ['programme_id' => 1,  'department_id' => 22, 'name' => 'HND SLT(BIOLOGY/MICROBIOLOGY)'],
            ['programme_id' => 1,  'department_id' => 22, 'name' => 'HND MICROBIOLOGY OPTION'],
            ['programme_id' => 2,  'department_id' => 22, 'name' => 'ND Science Laboratory Technology'],
            ['programme_id' => 2,  'department_id' => 23, 'name' => 'ND Social Development'],
            ['programme_id' => 3,  'department_id' => 23, 'name' => 'NDS Social Development'],
            ['programme_id' => 5,  'department_id' => 23, 'name' => 'PD Social Development'],
            ['programme_id' => 5,  'department_id' => 24, 'name' => 'Diploma Sharia and Civil Law'],
            ['programme_id' => 5,  'department_id' => 26, 'name' => 'Diploma Mass Communication'],
            ['programme_id' => 2,  'department_id' => 27, 'name' => 'ND Library and Information Science'],
            ['programme_id' => 6,  'department_id' => 28, 'name' => 'PGD Education'],

        ];
        DB::table('courses')->insert($courses);
    }
}