<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DepartmentProgrammeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['programme_id' => 1, 'department_id' => 1],
            ['programme_id' => 1, 'department_id' => 2],
            ['programme_id' => 1, 'department_id' => 3],
            ['programme_id' => 1, 'department_id' => 5],
            ['programme_id' => 1, 'department_id' => 6],
            ['programme_id' => 1, 'department_id' => 7],
            ['programme_id' => 1, 'department_id' => 8],
            ['programme_id' => 1, 'department_id' => 9],
            ['programme_id' => 1, 'department_id' => 10],
            ['programme_id' => 1, 'department_id' => 11],
            ['programme_id' => 1, 'department_id' => 12],
            ['programme_id' => 1, 'department_id' => 13],
            ['programme_id' => 1, 'department_id' => 14],
            ['programme_id' => 1, 'department_id' => 15],
            ['programme_id' => 1, 'department_id' => 16],
            ['programme_id' => 1, 'department_id' => 17],
            ['programme_id' => 1, 'department_id' => 20],
            ['programme_id' => 1, 'department_id' => 21],
            ['programme_id' => 1, 'department_id' => 22],
            ['programme_id' => 2, 'department_id' => 1],
            ['programme_id' => 2, 'department_id' => 2],
            ['programme_id' => 2, 'department_id' => 3],
            ['programme_id' => 2, 'department_id' => 4],
            ['programme_id' => 2, 'department_id' => 5],
            ['programme_id' => 2, 'department_id' => 6],
            ['programme_id' => 2, 'department_id' => 7],
            ['programme_id' => 2, 'department_id' => 8],
            ['programme_id' => 2, 'department_id' => 9],
            ['programme_id' => 2, 'department_id' => 10],
            ['programme_id' => 2, 'department_id' => 11],
            ['programme_id' => 2, 'department_id' => 12],
            ['programme_id' => 2, 'department_id' => 13],
            ['programme_id' => 2, 'department_id' => 14],
            ['programme_id' => 2, 'department_id' => 15],
            ['programme_id' => 2, 'department_id' => 16],
            ['programme_id' => 2, 'department_id' => 17],
            ['programme_id' => 2, 'department_id' => 20],
            ['programme_id' => 2, 'department_id' => 21],
            ['programme_id' => 2, 'department_id' => 22],
            ['programme_id' => 2, 'department_id' => 23],
            ['programme_id' => 2, 'department_id' => 27],
            ['programme_id' => 3, 'department_id' => 1],
            ['programme_id' => 3, 'department_id' => 2],
            ['programme_id' => 3, 'department_id' => 3],
            ['programme_id' => 3, 'department_id' => 4],
            ['programme_id' => 3, 'department_id' => 5],
            ['programme_id' => 3, 'department_id' => 6],
            ['programme_id' => 3, 'department_id' => 7],
            ['programme_id' => 3, 'department_id' => 8],
            ['programme_id' => 3, 'department_id' => 9],
            ['programme_id' => 3, 'department_id' => 10],
            ['programme_id' => 3, 'department_id' => 11],
            ['programme_id' => 3, 'department_id' => 12],
            ['programme_id' => 3, 'department_id' => 13],
            ['programme_id' => 3, 'department_id' => 14],
            ['programme_id' => 3, 'department_id' => 15],
            ['programme_id' => 3, 'department_id' => 16],
            ['programme_id' => 3, 'department_id' => 17],
            ['programme_id' => 3, 'department_id' => 20],
            ['programme_id' => 3, 'department_id' => 21],
            ['programme_id' => 3, 'department_id' => 23],
            ['programme_id' => 3, 'department_id' => 27],
            ['programme_id' => 4, 'department_id' => 18],
            ['programme_id' => 4, 'department_id' => 19],
            ['programme_id' => 4, 'department_id' => 25],
            ['programme_id' => 5, 'department_id' => 1],
            ['programme_id' => 5, 'department_id' => 2],
            ['programme_id' => 5, 'department_id' => 3],
            ['programme_id' => 5, 'department_id' => 5],
            ['programme_id' => 5, 'department_id' => 6],
            ['programme_id' => 5, 'department_id' => 7],
            ['programme_id' => 5, 'department_id' => 8],
            ['programme_id' => 5, 'department_id' => 9],
            ['programme_id' => 5, 'department_id' => 10],
            ['programme_id' => 5, 'department_id' => 11],
            ['programme_id' => 5, 'department_id' => 13],
            ['programme_id' => 5, 'department_id' => 14],
            ['programme_id' => 5, 'department_id' => 15],
            ['programme_id' => 5, 'department_id' => 16],
            ['programme_id' => 5, 'department_id' => 17],
            ['programme_id' => 5, 'department_id' => 21],
            ['programme_id' => 5, 'department_id' => 23],
            ['programme_id' => 5, 'department_id' => 24],
            ['programme_id' => 5, 'department_id' => 26],
            ['programme_id' => 5, 'department_id' => 27],
            ['programme_id' => 6, 'department_id' => 1],
            ['programme_id' => 6, 'department_id' => 5],
            ['programme_id' => 6, 'department_id' => 3],
            ['programme_id' => 6, 'department_id' => 7],
            ['programme_id' => 6, 'department_id' => 9],
            ['programme_id' => 6, 'department_id' => 10],
            ['programme_id' => 6, 'department_id' => 11],
            ['programme_id' => 6, 'department_id' => 12],
            ['programme_id' => 6, 'department_id' => 14],
            ['programme_id' => 6, 'department_id' => 16],
            ['programme_id' => 6, 'department_id' => 21],
            ['programme_id' => 6, 'department_id' => 28],


        ];
        DB::table('department_programmes')->insert($data);
    }
}